package exception.part432;

import exception.part432.CustomException;

public class Demo {
    public static void main(String[] args) {
        throw new CustomException("Custom exception");
    }

}
